[versions]
spigot = "1.8.8-R0.1-SNAPSHOT"
lombok = "1.18.38"
inventory = "2.0.3"
command = "1.3.1"
placeholderapi = "2.11.7"

[libraries]
spigot = { module = "org.spigotmc:spigot", version.ref = "spigot" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
inventory = { module = "com.github.HenryFabio:inventory-api", version.ref = "inventory" }
command = {module = "com.github.SaiintBrisson.command-framework:bukkit", version.ref = "command"}
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }